import Head from "next/head";
import { motion } from "framer-motion";


export default function Home() {

	const images = [
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/2.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/3.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/4.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/5.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/6.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/7.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/1.png",
	]

	return (
		<>
			<Head>
				<title>Triomics Test</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="min-h-screen w-full items-center justify-center">
				<div className="border-2 carousal w-[95vw] mt-4 inline-block overflow-hidden  ml-[2.5vw] rounded-lg ">
					<div className="carousal-track rounded-md ">
						{
							images.map((image) => {
								return (
									<img key={`${image}-once`} alt="Carousal Image" src={image} className="w-52" />
								)
							})
						}
					</div>
					<div className="carousal-track rounded-md ">
						{
							images.map((image) => {
								return (
									<img key={`${image}-once`} alt="Carousal Image" src={image} className="w-52" />
								)
							})
						}
					</div>
				</div>
			</main>
		</>
	);
}
