import Head from "next/head";
import { motion } from "framer-motion";


export default function Home() {

	const images = [
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/2.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/3.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/4.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/5.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/6.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/7.png",
		"https://s3-us-west-2.amazonaws.com/s.cdpn.io/557257/1.png",
	]

	return (
		<>
			<Head>
				<title>Triomics Test</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="">
				<div className="w-[90vw] ml-[5vw] overflow-hidden bg-gradient-to-r from-white from-0% via-50% to-100% to-white via-transparent rounded-lg">
					<div className="border-2 carousal -z-10 mt-4 relative overflow-hidden   rounded-lg ">
						<div className="carousal-track rounded-md ">
							{
								images.map((image) => {
									return (
										<div key={`${image}-first`} className="w-[200px]" >
											<img alt="Carousal Image" src={image} />
										</div>
									)
								})
							}
						</div>
						<div className="carousal-track rounded-md ">
							{
								images.map((image) => {
									return (
										<div key={`${image}-twice`} className="w-[200px]" >
											<img alt="Carousal Image" src={image} />
										</div>
									)
								})
							}
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
